#ifndef DATABASE_H
#define DATABASE_H

const DATABASE_ID IDRIVEBMRDB_SERVER=20;
const DATABASE_ID IDRIVEBMRDB_SERVER_FILES = 23;
const DATABASE_ID IDRIVEBMRDB_SERVER_FILES_DEL = 31;
const DATABASE_ID IDRIVEBMRDB_SERVER_LINKS = 24;
const DATABASE_ID IDRIVEBMRDB_SERVER_LINK_JOURNAL = 25;
const DATABASE_ID IDRIVEBMRDB_SERVER_SETTINGS=30;
const DATABASE_ID IDRIVEBMRDB_SERVER_FILES_NEW = 26;
const DATABASE_ID IDRIVEBMRDB_SETTINGS = 27;

#endif //DATABASE_H
